### PR TITLE
Feature/copyright

### LINKED ISSUE #30: Copyright decorator
To be legal - whenever the map is displayed and on any medium - we must show appropriate copyright.

QGIS only supports this with a copyright decorator. Let's implement it - and display the deduplicated copyright from TileJSON - as JavaScript viewers do.

### PR DESCRIPTION
**Pull request by Kanahiro**
close #30 

This include #31 commits.

Implementation to add Copyright decoration, text get from tiles.json.
Wrote to always show an attribution of a layer selected in the tree.

### CODE REVIEW

**Comment by lazaa32** [comment]
@Kanahiro, few bugs I found:

- decorator is not displayed if I try to export map to PNG/PDF (Project/Import/Export/Export Map to Image...) The checkbox `Draw active decorations` displays `none`.

image

- Copyright decorator is displayed only if layer is selected. IMHO decorator should be displayed when MapTiler layer is enabled.
MapTilert layer is selected and enabled - decorator is displayed correctly:
image

Another vector layer is selected,  MapTiler layer is enabled - copyright is not displayed (but should be):
image

MapTiler layer is selected but not enabled - decorator is displayed (it should not):
image

MapTiler layer is not selected nor enabed - decorator is not displayed (correct):
image

**Comment by klokan** [comment]
It sounds as a wrong decision on how to implement the copyright...
It looks like we really have to work with the Project-wise copyright decorator - which does not have these issues, right?

**Comment by Kanahiro** [comment]
Thank you for reviewing.
Firstly I forget to think about PDF/PNG exporting and so implemented no-Project-wise one, I'll fix this.
Also, I have to clarify which copyright should be shown and active, when some MapTiler layers are in a project, most front one or newest?

**Comment by lazaa32** [comment]
There should be shown deduplicated copyrights. For each enabled layer there should be its copyright but if more layers have same copyright it will be shown only once.

**Comment by lazaa32** [comment]
Possible solution mentioned in #30.

**Comment by Kanahiro** [comment]
I've fixed Copyright Decoration as you mentioned.
Thank you for your advise and please try it.

**Comment by lazaa32** [comment]
I've tested the commits you've pushed so far and it looks everything is OK. Please, @Kanahiro, let me know when all commits for this issue are here I will merge.

**Comment by Kanahiro** [comment]
Thank you for testing @lazaa32 , all commits has been pushed already.

**Pull request merged**
