### PR TITLE
Replaced visual assets, Fixed New connection UI, 3.4LTR support.

### LINKED ISSUE #3: Replace the visual assets
MapTiler designer should provide the icons for interface according to the wireframes in the SVG of right size.

Similar to: https://github.com/qgis/QGIS/blob/master/images/themes/default/mIconGeonode.svg - so canvas size 24x24px.

Also the logotype of the MapTiler in Dark and White mode as SVG (for pixels roughly of the size of the screen - so SVG canvas width 250px).

### LINKED ISSUE #7: Plugin is not visible in Browser in QGIS 3.4
If I try to install the plugin in qgis 3.4 LTS. The Geocoding is present and I can correctly add maptiler key on it but there is no plugin displayed in a Browser. Tested on Mac and ubuntu. Console said that the plugin is correctly loaded. In the log, there is only one warning with depreciation:

```
2020-05-11T15:22:18     WARNING    warning:/usr/lib/python3/dist-packages/osgeo/gdal.py:112: DeprecationWarning: ogr.py was placed in a namespace, it is now available as osgeo.ogr
```

### PR DESCRIPTION
**Pull request by Kanahiro**
close #3
close #7 
related #8  

- Replaced visual assets
- Fixed New connection UI
- Removed unused module importing
- autopep8 Formatting
- fix initiation a browser item to support QGIS3.4

I'll improve context menu as soon as a mockup is uploaded. #8

### CODE REVIEW

**Comment by klokan** [comment]
@Kanahiro could you please resolve the conflict - then we can merge. Thank you very much!

**Comment by Kanahiro** [comment]
The conflict already resolved.

**Comment by Kanahiro** [comment]
スクリーンショット 2020-05-22 11 32 10

Now automatically detected darkmode or not, and show imgs depending on the mode.

**Comment by Kanahiro** [comment]
close #10

**Comment by lazaa32** [comment]
Testing the PR. Great job, it looks good. Please improve contextual menu when mockups are provided.

- [x] Detect test mode. #10 
- [x] Replace visual assets #3 
- [x]  Plugin is not visible in Browser in QGIS 3.4 #7
tested in 3.10 and 3.14. Both installing/uninstalling require restart QGIS to show/unshow MapTiler plugin in Browser panel. But I think it's normal though.
- [ ] Contextual dialog #8  
The dialog needs to be further improved.
Labels seem to use different font/font size. Text fields have different heights.
dialog
Modal window should not be resizable.
dialog2
Also please add ellipsis (triple dot) after Add new connection

**Pull request merged**
