### PR TITLE
Support Sprite/fill-pattern

### PR DESCRIPTION
**Pull request by Kanahiro**
Related #69 

https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/
In the specification, Sprites can be used in background-pattern, fill-pattern, line-pattern, fill-extrusion-pattern and icon-image.

I tried each points one by one, first, I've implemented fill-pattern-sprite.
I'll try line-pattern next.

### CODE REVIEW

**Comment by Kanahiro** [comment]
finished.

**Comment by Kanahiro** [comment]
<s>I'll try line-pattern next.</s>
I'll start with icon-image because line-pattern may not be popular.

**Comment by lazaa32** [comment]
Hi Kanahiro, I tested your PR so far and it looks great! Especially Toner map improved a lot, thanks!Let me know, when you are done with other patterns (but I think fill-pattern was the most important) and i will test it again and merge.

**Comment by Kanahiro** [comment]
Thank you for reviewing!
I'm trying icon-image now and, when complete it, will send another pull request.
So, if this pull request is good to you, it's ok to merge this.

**Comment by lazaa32** [comment]
Ok, merging now.

**Pull request merged**
