### PR TITLE
Added action in cotextual to open customize page

### LINKED ISSUE #66: Add 'Customize' contextual menu item
For all preset maps that are hosted on our server we want to add new item `Customize in Cloud ⇑` in contextual menu of a map.
Contextual menu will look as follow:
- Add as Raster
- Add as Vector
- Remove
- ----------- (Qt Menu Separator)
- Customize in Cloud ⇑

`Customize in Cloud` will not appear for user's custom map.
After clicking on the item a browser should open at Customize tool for matching map:
E.g. for Basic: https://cloud.maptiler.com/customize/#basic/1/0/0

### PR DESCRIPTION
**Pull request by Kanahiro**
close #66 

Implemented actions to open customize page in contextual menu.
Because some style don't have customize page as you know, add the action to only items having 'customize_url', hard-coded in mapdatasets.py.

### CODE REVIEW

**Comment by lazaa32** [comment]
Could you please add UTF symbol ↗ NORTH EAST ARROW at the end of `Customize in cloud ↗`
https://www.w3schools.com/charsets/tryit.asp?deci=8599

**Comment by lazaa32** [comment]
Your solution of hard-coded customize_rul for mapdatasets is fine.

**Comment by Kanahiro** [comment]
Thank you for reviewing. I've fixed.

**Comment by lazaa32** [comment]
Tested. Works great. Thank you. Closing.

**Pull request merged**
