### PR TITLE
support tiles.json for vectortile

### PR DESCRIPTION
**Pull request by Kanahiro**
detail #8 

In latest version, tiles.json is treated as only Raster but tiles.json can be defined for Vectortile.
In this pullrequest, some codes are added to support tiles.json for Vectortile.

Also added some refactoring.

### CODE REVIEW

**Comment by lazaa32** [comment]
I tested your changes and for both vector and raster tile.json it works fine. Raster tile.json is added as raster, vector tile.json is added as vector. However if I add style.json for any vector map I got Key Error:
```
Key Error ['format']
_is_vector_json [browser_mapitem.py:101]
```

**Comment by Kanahiro** [comment]
Thank you for response.
I made some fix to support user-custom style.json, please try it.

**Comment by lazaa32** [comment]
I tested your changes, and tried to add e.g. Toner map from Add a new map... dialog window using this url: https://api.maptiler.com/maps/toner/style.json?key=m6dxIgKVTnvERWrCmvUm and I got another error:
```
AttributeError
'NoneType' object has no attribute 'get'
_add_vector_to_canvas [browser_mapitem.py:175]
```

**Comment by Kanahiro** [comment]
I've fixed a problem you mentioned, thanks.

**Comment by lazaa32** [comment]
It works well for both raster and vector maps, both style.json and tile.json if the maps are hosted at api.maptiler.com. It should be also possible to add style.json/tile.json for a map hosted by different organizations and on different infrastructure.  E.g.: http://tileserver.maptiler.com/us-subway.json
Please, fix api key handelling, because now I am getting error:
```
JSONDecodeError
Expecting value: line 1 column 1 (char 0)
```
Because of the API key joined to the url:
`json_url = {str} 'http://tileserver.maptiler.com/us-subway.jsonm6dxIgKVTnvERWrCmvUm'`

**Comment by Kanahiro** [comment]
I've pushed some fix.
- API-key handling
- style.json parsing
- vector tile importing order

**Comment by lazaa32** [comment]
Still not working for me if I try to add tiles.json for raster:
`http://tileserver.maptiler.com/grandcanyon.json`
`http://tileserver.maptiler.com/ruhama-17-2-16.json`
Neither for vector:
`http://tileserver.maptiler.com/us-subway.json`

Map is added to list of layers but no data are displayed.

**Comment by lazaa32** [comment]
Sorry, it looks like a problem on tileserver side. I tried different server and it works OK:
`https://maps.geoapify.com/v1/styles/positron-blue/style.json?apiKey=95d293ca5c1747adae9d00ee3dba4f18`

**Comment by Kanahiro** [comment]
Ok, I also think so too and was going to tell you that :)
Please tell me if any other problem is remained.

**Comment by lazaa32** [comment]
It looks good. If any problem occurs for a specific tile provider we will open a ticket. Merging now.

**Pull request merged**
