### PR TITLE
#105 Fix to ignore deprecation warn

### PR DESCRIPTION
**Pull request by Kanahiro**
Related #105 

Fixed to ignore Deprecation Warning in Python.
I can reproduce Deprecation Warning but the plugin still working in my env.
So, I'm not sure this fix make sense. Needs to be tested. @rugbygis Could you try this?

### CODE REVIEW

**Comment by rugbygis** [comment]
Thanks for the email Kanahiro but I'm not a coder or developer just a user and I don't know what to do or what you mean merge or pull. Sorry you'll have to explain the process I need to do to test this in totally idiot terms!

**Comment by lazaa32** [comment]
No worries, it is not difficult at all @rugbygis:

1. First, please uninstall official version of plugin from your QGIS. (Top Menu/Plugins/Manage and Install Plugins.../Installed -> Find MapTiler plugin from searching field -> click Uninstall)
2. Then click on this [link](https://github.com/maptiler/qgis-maptiler-plugin/tree/fix/%23105_deprecation_warning)  which leads to different branch where the fix from Kanahiro is implemented.
3. Click on `Clone` button and then click on `Download ZIP`
4. Save zip file to your disk
5. Open QGIS and install new version of plugin: Top Menu/Plugins/Manage and Install Plugins.../Install from ZIP -> choose ZIP file from your disk -> click on Install Plugin
6. Restart QGIS
7. Try add map to QGIS whether you are still getting error.

Thank you very much for testing.

**Comment by rugbygis** [comment]
Still getting an error and have checked my API key and all is well - should I create a different key to see if that is the cause?

**Comment by lazaa32** [comment]
> Still getting an error and have checked my API key and all is well - should I create a different key to see if that is the cause?

It is the most likely not a problem of your API key. We will try to fix it as soon as possible.

**Comment by lazaa32** [comment]
@Kanahiro 
Is it possible to catch the warning? Example [here](https://stackoverflow.com/questions/15933741/how-do-i-catch-a-numpy-warning-like-its-an-exception-not-just-for-testing/15934081#15934081).

**Comment by rugbygis** [comment]
Sorry again guys but I look at that page and have no idea - how do I use it, what do I do with it?  I'm sorry but I'm way, way outside my depth here!

**Comment by lazaa32** [comment]
@rugbygis Did you manage to uninstall your old version and install new one as I described in the [comment](https://github.com/maptiler/qgis-maptiler-plugin/pull/114#issuecomment-650168614)? Do you still get error even in the new version?

**Comment by rugbygis** [comment]
I did uninstall and install the new one but still get the error.

**Comment by lazaa32** [comment]
OK, thank you. We will let you know as soon as we find the solution.

**Comment by rugbygis** [comment]
Thanks Adam

**Pull request merged**
