### PR TITLE
Prototype - Raster map loading

### PR DESCRIPTION
**Pull request by Kanahiro**
Hello, I'm Kanahiro Iguchi working at MIERUNE inc.
Based on the meeting, we made a prototype of the plugin.

## Usage
- To complete install this plugin, user have to re-launch QGIS application.
- Once installed, MapTiler will be added to Browser
- API-key is needed to be inputed, by right-clicking MapTiler Item.

## Spec
- Categorized Maps as some collections, Local, Standard and User.
- Only User collection can be editable by user.

### CODE REVIEW

**Comment by klokan** [comment]
Excellent! Thank you. We will try & test it.

@daliborjanak could you assist, please?

**Comment by klokan** [comment]
It does run without any warning on QGIS 3.12 on my Mac.
Screenshot 2020-04-06 at 17 34 40 (2)

**Comment by Kanahiro** [comment]
Sorry for delay, I have fixed to show MapTiler icon on the API-KEY config dialog.
Next, I will add Geocoding function with MapTiler API.

**Comment by klokan** [comment]
Thank you a lot for the recent progress @Kanahiro 

Feedback and V1 wireframes for the interface:
https://docs.google.com/presentation/d/1CQKYTI9Bi_goKVVQogeFT4e26EsvvAG7f_73McdsEAk/edit#slide=id.p

**Comment by Kanahiro** [comment]
Hello @klokan, thank you for response.
Now almost features you suggested are already implemented, only "recently used maps" function is not, and it takes some time than others, I think.
Please try them.

**Comment by Kanahiro** [comment]
1. Current Interface
maptiler_plugin_interface

2. Browser Behavior
maptiler_browser_spec

**Comment by klokan** [comment]
Thank you very much! Merging it into master now.

**Pull request merged**
