### PR TITLE
Fix/reopen geocoding refactor

### PR DESCRIPTION
**Pull request by Kanahiro**
Sorry for confusing.
reopen #54 .

### CODE REVIEW

**Comment by lazaa32** [comment]
I tried to look up a street name (line feature) and it was found but in layer list it doesn't have check box and does not have a line layer icon.
Query string: `Beethovenstrasse, Zurich`
image

**Comment by lazaa32** [comment]
Raster maps still appear in group of vector map. Not everytime, just when vector map group was selected before. Our desired behaviour is to always add raster map to top/root node of layer tree.
image

**Comment by lazaa32** [comment]
> Raster maps still appear in group of vector map. Not everytime, just when vector map group was selected before. Our desired behaviour is to always add raster map to top/root node of layer tree.
> image

Sorry, I noticed now it is solved in different PR and it works.

**Comment by Kanahiro** [comment]
> I tried to look up a street name (line feature) and it was found but in layer list it doesn't have check box and does not have a line layer icon.
Query string: Beethovenstrasse, Zurich

Although I can't reproduce your case, I think that problem may be caused by adding invalid vlayer.
I added codes adding valid vlayer only, please try it.

**Comment by lazaa32** [comment]
I tried different addresses and some of them are now added as line layer. Some of them still don't display correctly. For them I also get error in terminal:
`ERROR 6: Update from inline definition not supported`
 Are you able to add any address with street name into Geocoding and see correct results?

image

**Comment by Kanahiro** [comment]
Thank for information. I can reproduce your case.
I found the problem occurs in adding Geomtry Collection.
On specification, GeoJSON  can contain some types of features, Point, LineString and Polygon, but QGIS are not able to accept some types in one layer.

There are three ways in my opinion.
1. Parse Geometry Collection into one layer containing one type, one feature.
2. Stop adding vector layer.

 I think it is better to stop adding because MapCanvas will focus target correctly without a layer.

**Comment by lazaa32** [comment]
+1 for stop adding vector layer. I think @klokan asked if it is possible not to add layer from geocoding query on our last call.
Please fix it in a way that after QGIS gets response from geocoding API it only zoom to the extent of the feature but no layer is added (no line layer, no point layer, none layer). Thanks :)

**Comment by Kanahiro** [comment]
Fixed to stop adding vlayer, please try it.

**Comment by lazaa32** [comment]
Tested. No layers from geocoding added. Good job, thank you. Merging...

**Pull request merged**
